[project]
name = "wsl-unsloth-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mwparserfromhell>=0.7.2",
    "mwxml>=0.3.6",
    "unsloth>=2025.12.8",
]
